// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmqCezTZ0Emt2Zp60o7hPBm25DjcaC8zA',
    appId: '1:1030826698057:web:b4b0529ab112acd1cae698',
    messagingSenderId: '1030826698057',
    projectId: 'pos-flutter-app-74071',
    authDomain: 'pos-flutter-app-74071.firebaseapp.com',
    storageBucket: 'pos-flutter-app-74071.firebasestorage.app',
    measurementId: 'G-36TQ3T5BX4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfdEOTX7BFVWWMDLeQk1YF_KRHAiUz_f4',
    appId: '1:1030826698057:android:a591d004b230a05fcae698',
    messagingSenderId: '1030826698057',
    projectId: 'pos-flutter-app-74071',
    storageBucket: 'pos-flutter-app-74071.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMV_7IuR_F5mdNwnTxI66PX_WtBpuZzJ4',
    appId: '1:1030826698057:ios:65cb25eb93921d43cae698',
    messagingSenderId: '1030826698057',
    projectId: 'pos-flutter-app-74071',
    storageBucket: 'pos-flutter-app-74071.firebasestorage.app',
    iosClientId: '1030826698057-25qdk33oj71a9a87s82eb185f23ml7v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.posCashierApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMV_7IuR_F5mdNwnTxI66PX_WtBpuZzJ4',
    appId: '1:1030826698057:ios:65cb25eb93921d43cae698',
    messagingSenderId: '1030826698057',
    projectId: 'pos-flutter-app-74071',
    storageBucket: 'pos-flutter-app-74071.firebasestorage.app',
    iosClientId: '1030826698057-25qdk33oj71a9a87s82eb185f23ml7v0.apps.googleusercontent.com',
    iosBundleId: 'com.example.posCashierApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmqCezTZ0Emt2Zp60o7hPBm25DjcaC8zA',
    appId: '1:1030826698057:web:6fe229c0c881caf2cae698',
    messagingSenderId: '1030826698057',
    projectId: 'pos-flutter-app-74071',
    authDomain: 'pos-flutter-app-74071.firebaseapp.com',
    storageBucket: 'pos-flutter-app-74071.firebasestorage.app',
    measurementId: 'G-M2W7JTVECX',
  );

}